# Generated by Django 6.0.3 on 2026-03-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('section', models.CharField(choices=[('home', 'Главная страница'), ('theory', 'Теория')], default='theory', max_length=10, verbose_name='Раздел')),
                ('content', models.TextField(verbose_name='Текст статьи')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
