# Generated by Django 6.0.3 on 2026-03-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_article_options_article_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_position',
            field=models.CharField(choices=[('top', 'Сверху (на всю ширину)'), ('left', 'Слева (обтекание)'), ('right', 'Справа (обтекание)')], default='top', max_length=10, verbose_name='Положение фото'),
        ),
    ]
