# Generated by Django 6.0.3 on 2026-04-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_article_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='article',
            name='reading_time',
            field=models.PositiveIntegerField(blank=True, help_text='Оставьте пустым для автоматического расчета', null=True, verbose_name='Время чтения (мин.)'),
        ),
    ]
