# Generated by Django 6.0.3 on 2026-04-15 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_userprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок задания')),
                ('description', models.TextField(verbose_name='Описание (что нужно сделать)')),
                ('task_text', models.TextField(help_text='То, что пользователь должен расшифровать', verbose_name='Текст задания (шифровка/код)')),
                ('correct_answer', models.CharField(max_length=200, verbose_name='Правильный ответ')),
                ('hint', models.TextField(blank=True, null=True, verbose_name='Подсказка')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='easy', max_length=10, verbose_name='Сложность')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Практическое задание',
                'verbose_name_plural': 'Практические задания',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='reading_time',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Текст статьи'),
        ),
        migrations.CreateModel(
            name='UserPracticeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.practicetask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс практики',
                'verbose_name_plural': 'Прогресс практики',
                'unique_together': {('user', 'task')},
            },
        ),
    ]
