# Generated by Django 6.0.3 on 2026-04-15 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_practicetask_remove_article_reading_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicetask',
            name='related_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.article', verbose_name='Связанная статья (открывает доступ)'),
        ),
    ]
