# Generated by Django 6.0.3 on 2026-04-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_cryptotool'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visualizer_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на визуализатор кода (Python Tutor)'),
        ),
    ]
