# Generated by Django 6.0.3 on 2026-04-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_article_visualizer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='visualizer_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Ссылка на визуализатор'),
        ),
    ]
