# Generated by Django 6.0.3 on 2026-04-17 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_alter_article_visualizer_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpracticeprogress',
            options={},
        ),
        migrations.AddField(
            model_name='cryptotool',
            name='js_logic',
            field=models.TextField(blank=True, null=True, verbose_name='JS код алгоритма'),
        ),
        migrations.AlterField(
            model_name='cryptotool',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cryptotool',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.practicetask', verbose_name='Связанная задача'),
        ),
        migrations.AlterField(
            model_name='cryptotool',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cryptotool',
            name='tool_type',
            field=models.CharField(max_length=50, verbose_name='Тип (технический)'),
        ),
        migrations.AlterField(
            model_name='practicetask',
            name='related_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.article', verbose_name='Связанная статья'),
        ),
        migrations.AlterField(
            model_name='practicetask',
            name='task_text',
            field=models.TextField(verbose_name='Текст задания (шифровка/код)'),
        ),
    ]
