# Generated by Django 6.0.3 on 2026-04-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_alter_userpracticeprogress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['id'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='practicetask',
            options={'ordering': ['id'], 'verbose_name': 'Практическое задание', 'verbose_name_plural': 'Практические задания'},
        ),
    ]
