# Generated by Django 6.0.3 on 2026-04-19 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_userprofile_full_name_userprofile_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpracticeprogress',
            options={'ordering': ['time_taken']},
        ),
        migrations.AddField(
            model_name='userpracticeprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Решено'),
        ),
        migrations.AddField(
            model_name='userpracticeprogress',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время начала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpracticeprogress',
            name='time_taken',
            field=models.IntegerField(blank=True, null=True, verbose_name='Затрачено секунд'),
        ),
        migrations.AlterField(
            model_name='userpracticeprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения'),
        ),
    ]
