# Generated by Django 6.0.3 on 2026-04-19 12:43

import django.core.validators
import django.db.models.deletion
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_alter_userpracticeprogress_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptotool',
            options={'verbose_name': 'Криптографический инструмент', 'verbose_name_plural': 'Криптографические инструменты'},
        ),
        migrations.AlterModelOptions(
            name='userpracticeprogress',
            options={'ordering': ['time_taken'], 'verbose_name': 'Прогресс по заданию', 'verbose_name_plural': 'Прогресс по заданиям'},
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={'verbose_name': 'Прогресс по статье', 'verbose_name_plural': 'Прогресс по статьям'},
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), portal.models.validate_image_size], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='cryptotool',
            name='js_logic',
            field=models.TextField(blank=True, null=True, verbose_name='JavaScript логика (encrypt/decrypt)'),
        ),
        migrations.AlterField(
            model_name='cryptotool',
            name='tool_type',
            field=models.CharField(max_length=50, verbose_name='Тип инструмента (caesar, vigenere и т.д.)'),
        ),
        migrations.AlterField(
            model_name='practicetask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='practicetask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='userpracticeprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала решения'),
        ),
        migrations.AlterField(
            model_name='userpracticeprogress',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.practicetask', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='userpracticeprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), portal.models.validate_image_size], verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Приватный профиль (скрыть имя)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
