# Generated by Django 6.0.3 on 2026-04-19 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_alter_cryptotool_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptotool',
            name='js_logic',
        ),
        migrations.AlterField(
            model_name='cryptotool',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.practicetask', verbose_name='Связанная задача (для разблокировки)'),
        ),
        migrations.AlterField(
            model_name='cryptotool',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название инструмента'),
        ),
        migrations.AlterField(
            model_name='cryptotool',
            name='tool_type',
            field=models.CharField(help_text='Например: caesar, vigenere, atbash, scytale, playfair и т.д.', max_length=50, verbose_name='Тип шифра'),
        ),
        migrations.AlterField(
            model_name='practicetask',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='practicetask',
            name='task_text',
            field=models.TextField(verbose_name='Текст задания (шифровка)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Приватный профиль'),
        ),
    ]
