# Generated by Django 6.0.3 on 2026-04-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_remove_cryptotool_js_logic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptotool',
            name='tool_type',
            field=models.CharField(help_text='Например: caesar, vigenere, atbash', max_length=50, verbose_name='Тип шифра'),
        ),
    ]
